services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    restart: always

  frontend:
    build: 
      context: .
      dockerfile: src/Dockerfile
    volumes:
      - ./build:/usr/share/nginx/html
    environment:
      - NODE_ENV=production
    restart: always

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

